# Generated by Django 3.2 on 2023-04-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images-predicted/')),
                ('predicted_label', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='correctedprediction',
            name='image',
            field=models.ImageField(upload_to='images-corrections/'),
        ),
    ]
